{{-- Left menu generated by Voyager --}}
<ul class="nav-left">
    @foreach($items as $menu_item)
        <li>
        	<a href="{{ $menu_item->link() }}">{{ $menu_item->title }}</a>
        </li>
    @endforeach
</ul>

{{-- Authentication Links --}}
<ul class="nav-right">
    @guest
        <li class="nav-item">
            <a class="nav-link" href="{{ route('login') }}">{{ __('Login') }}</a>
        </li>
        @if (Route::has('register'))
            <li class="nav-item">
                <a class="nav-link" href="{{ route('register') }}">{{ __('Sign Up') }}</a>
            </li>
        @endif
    @else
        <li class="nav-item-dropdown">
            <a id="user-dropdown-toggle" class="nav-link" href="{{ route('profile.edit') }}" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" v-pre>
                {{ Auth::user()->name }} <span class="caret"></span>
            </a>

            <div class="custom-dropdown-menu">
                <ul class="custom-dropdown-menu-ul">
                    <li>
                        <a href="{{ route('profile.edit') }}">My Profile</a>
                    </li>
                    <li>
                        <a href="#">My Orders</a>
                    </li>
                    <li>
                        <a href="{{ route('logout') }}"
                           onclick="event.preventDefault();
                                    document.getElementById('logout-form').submit();">
                            {{ __('Logout') }}
                        </a>

                        <form id="logout-form" action="{{ route('logout') }}" method="POST" style="display: none;">
                            @csrf
                        </form>
                    </li>
                </ul>
            </div>
        </li>
    @endguest

    <li>
        <a href="{{ route('wishlist.index') }}" title="Wishlist">
            <i class="far fa-heart"></i>
            @if (Cart::instance('wishlist')->count())
                <span class="wishlist-count">{{ Cart::instance('wishlist')->count() }}</span>
            @endif
        </a> 
    </li>

    <li>
        <a href="{{ route('cart.index') }}" title="Cart">
            <i class="fa fa-cart-plus"></i> 
            @if (Cart::instance('default')->count())
                <span class="cart-count">{{ Cart::instance('default')->count() }}</span>
            @endif
        </a> 
    </li>
</ul>

